alias g="git"
alias gs="git status"
alias ga="git add"
alias gaa="git add -A"
alias gc="git commit -m"
# gca is a function (functions/git/functions.zsh): add -A + commit, but
# only if there's something to commit -- not a plain "commit -am" alias.
alias gp="git push"
alias gpl="git pull"
alias gco="git checkout"
alias gcb="git checkout -b"
alias gb="git branch"
alias gd="git diff"
alias gl="git log --oneline --graph --decorate -20"
alias glog="git log --oneline --graph --decorate --all"
