set -g status-position bottom
set -g status-style bg=colour234,fg=colour137
set -g status-left-length 20
set -g status-right-length 50

set -g status-left '#[fg=colour235,bg=colour252,bold] #S #[fg=colour252,bg=colour234,nobold]'
set -g status-right '#[fg=colour233,bg=colour241,bold] %Y-%m-%d %H:%M #[fg=colour233,bg=colour245,bold] #h '

setw -g window-status-current-style fg=colour81,bg=colour238,bold
setw -g window-status-current-format ' #I:#W#F '
setw -g window-status-style fg=colour138,bg=colour235
setw -g window-status-format ' #I:#W#F '
